const express = require('express')
const port = 4000
const db = require('./db')
const app = express()
const router = require('./event/router')
const cors = require('cors')
const corsMiddleware = cors()
const bodyParser = require('body-parser')
const parserMiddleware = bodyParser.json()
app.use(corsMiddleware)
app.use(parserMiddleware)
app.use(router)
app.listen(port, ()=> console.log(`listening on port ${port}`))